-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 08:56:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine` DEFAULT CHARACTER SET utf8 ;
USE `cine` ;

-- -----------------------------------------------------
-- Table `cine`.`directores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`directores` (
  `id_director` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `fechaNac` DATE NOT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine`.`companias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`companias` (
  `id_companias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_companias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cine`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`peliculas` (
  `id_peliculas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `anoLanzamiento` DATE NULL,
  `duracion` INT NULL,
  `sinopsis` VARCHAR(250) NOT NULL,
  `id_compania` INT NOT NULL,
  `id_director` INT NOT NULL,
  PRIMARY KEY (`id_peliculas`),
  INDEX `fk_pelicula_compania_idx` (`id_compania` ASC),
  INDEX `fk_pelicula_director_idx` (`id_director` ASC),
  CONSTRAINT `fk_pelicula_compania`
    FOREIGN KEY (`id_compania`)
    REFERENCES `cine`.`companias` (`id_companias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_director`
    FOREIGN KEY (`id_director`)
    REFERENCES `cine`.`directores` (`id_director`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
